client:
    login: null
    password: null

server:
    host: "0.0.0.0"
    port: 2222
    listen_number: 1 # no need

service:
    emulate_terminal: "BashEmulateTerminal"
    executor: "LocalExecutor" # SimpleExecutor no need
    output: "FileOutHandler" # FileOutHandler, SocketOutHandler | in future:(TelegramOutHandler)
    logger: "DataBaseFileLogger" # FileLogger, DataBaseLogger
    server: "SSHServer" # in future: (HTTPServer, FTPServer)
    starter: "Starter"

emulate_terminal:
    color: False #no need
    time_to_block: 3600 # seconds

socket_out:
    server_ip: "127.0.0.1"
    server_port: 2525

path:
    ssh_keys_path: "server/ssh/ssh_keys/fake_ssh_host_key"
    file_out_path: "output/out.txt"
    logging_path: 'logger/logs/honey.db'